PRAGMA foreign_keys = ON;
CREATE TABLE platform_state (id INTEGER PRIMARY KEY CHECK (id = 1), revision INTEGER NOT NULL DEFAULT 0);
CREATE TABLE content_items (id INTEGER PRIMARY KEY, kind TEXT NOT NULL CHECK (kind = 'education'));
CREATE INDEX content_items_kind ON content_items(kind);
CREATE TABLE profile (id INTEGER PRIMARY KEY CHECK (id = 1), full_name TEXT NOT NULL);
CREATE TABLE profile_translations (profile_id INTEGER NOT NULL REFERENCES profile(id) ON DELETE CASCADE, locale TEXT NOT NULL CHECK (locale IN ('en','fr','ar')), headline TEXT NOT NULL, PRIMARY KEY(profile_id, locale));
CREATE INDEX profile_locale ON profile_translations(locale);
CREATE TABLE education (id INTEGER PRIMARY KEY REFERENCES content_items(id) ON DELETE CASCADE, start_date TEXT NOT NULL, end_date TEXT, school_url TEXT, display_order INTEGER NOT NULL DEFAULT 0 CHECK(display_order >= 0), is_visible INTEGER NOT NULL DEFAULT 0 CHECK(is_visible IN (0,1)));
CREATE INDEX education_visibility_order ON education(is_visible, display_order);
CREATE TABLE education_translations (education_id INTEGER NOT NULL REFERENCES education(id) ON DELETE CASCADE, locale TEXT NOT NULL CHECK(locale IN ('en','fr','ar')), school TEXT NOT NULL, degree TEXT NOT NULL, description TEXT NOT NULL, PRIMARY KEY(education_id, locale));
CREATE INDEX education_locale ON education_translations(locale);
CREATE TABLE cv_variants (id INTEGER PRIMARY KEY, slug TEXT NOT NULL UNIQUE, is_public INTEGER NOT NULL DEFAULT 0 CHECK(is_public IN (0,1)));
CREATE UNIQUE INDEX one_public_variant ON cv_variants(is_public) WHERE is_public = 1;
CREATE TABLE cv_variant_translations (variant_id INTEGER NOT NULL REFERENCES cv_variants(id) ON DELETE CASCADE, locale TEXT NOT NULL CHECK(locale IN ('en','fr','ar')), summary TEXT NOT NULL, PRIMARY KEY(variant_id, locale));
CREATE INDEX variant_locale ON cv_variant_translations(locale);
CREATE TABLE cv_variant_items (variant_id INTEGER NOT NULL REFERENCES cv_variants(id) ON DELETE CASCADE, content_item_id INTEGER NOT NULL REFERENCES content_items(id) ON DELETE CASCADE, position INTEGER NOT NULL CHECK(position >= 0), PRIMARY KEY(variant_id, content_item_id));
CREATE INDEX variant_item_content ON cv_variant_items(content_item_id);
CREATE TABLE audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, actor TEXT NOT NULL, action TEXT NOT NULL, entity TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX audit_entity_time ON audit_log(entity, created_at);
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_log BEGIN SELECT RAISE(ABORT, 'Audit log is append-only'); END;
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_log BEGIN SELECT RAISE(ABORT, 'Audit log is append-only'); END;
INSERT INTO platform_state(id, revision) VALUES (1, 0);
INSERT INTO profile(id, full_name) VALUES (1, 'MOHAMED CHARAF EDDINE DEGHBOUDJ');
INSERT INTO profile_translations(profile_id, locale, headline) VALUES (1, 'en', 'Sprint 0 technical proof — synthetic content'), (1, 'fr', 'Preuve technique Sprint 0 — contenu de test'), (1, 'ar', 'اختبار تقني — بيانات تجريبية');
INSERT INTO cv_variants(id, slug, is_public) VALUES (1, 'public', 1);
INSERT INTO cv_variant_translations(variant_id, locale, summary) VALUES (1, 'en', 'Technical proof of the CV pipeline. This is not a factual résumé.'), (1, 'fr', 'Vérification technique du moteur de CV. Ce document est un test.'), (1, 'ar', 'هذا المستند اختبار تقني لإنشاء السيرة الذاتية وليس سيرة ذاتية فعلية.');
