-- Foreign-key indexes and immutable identity membership.
CREATE INDEX cv_cache_locale ON cv_pdf_cache(locale);
CREATE INDEX experience_visibility_order ON experience(is_visible, display_order);
CREATE INDEX experience_locale ON experience_translations(locale);
CREATE INDEX experience_logo_media_id ON experience(logo_media_id);
CREATE INDEX achievements_visibility_order ON achievements(is_visible, display_order);
CREATE INDEX achievement_locale ON achievement_translations(locale);
CREATE INDEX achievements_media_id ON achievements(media_id);
CREATE INDEX certificates_visibility_order ON certificates(is_visible, display_order);
CREATE INDEX certificate_locale ON certificate_translations(locale);
CREATE INDEX certificates_original_media_id ON certificates(original_media_id);
CREATE INDEX certificates_public_media_id ON certificates(public_media_id);
CREATE INDEX initiatives_visibility_order ON initiatives(is_visible, display_order);
CREATE INDEX initiative_locale ON initiative_translations(locale);
CREATE INDEX initiatives_media_id ON initiatives(media_id);
CREATE INDEX skills_visibility_order ON skills(is_visible, display_order);
CREATE INDEX skill_locale ON skill_translations(locale);
CREATE INDEX languages_visibility_order ON languages(is_visible, display_order);
CREATE INDEX language_locale ON language_translations(locale);
CREATE INDEX project_categories_visibility_order ON project_categories(is_visible, display_order);
CREATE INDEX project_category_locale ON project_category_translations(locale);
CREATE INDEX projects_visibility_order ON projects(is_visible, display_order);
CREATE INDEX project_locale ON project_translations(locale);
CREATE INDEX projects_cover_media_id ON projects(cover_media_id);
CREATE INDEX articles_visibility_order ON articles(is_visible, display_order);
CREATE INDEX article_locale ON article_translations(locale);
CREATE INDEX articles_cover_media_id ON articles(cover_media_id);
CREATE TRIGGER education_kind_insert BEFORE INSERT ON education WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'education' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER education_kind_update BEFORE UPDATE OF id ON education WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'education' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER experience_kind_insert BEFORE INSERT ON experience WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'experience' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER experience_kind_update BEFORE UPDATE OF id ON experience WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'experience' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER achievements_kind_insert BEFORE INSERT ON achievements WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'achievement' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER achievements_kind_update BEFORE UPDATE OF id ON achievements WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'achievement' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER certificates_kind_insert BEFORE INSERT ON certificates WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'certificate' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER certificates_kind_update BEFORE UPDATE OF id ON certificates WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'certificate' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER initiatives_kind_insert BEFORE INSERT ON initiatives WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'initiative' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER initiatives_kind_update BEFORE UPDATE OF id ON initiatives WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'initiative' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER skills_kind_insert BEFORE INSERT ON skills WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'skill' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER skills_kind_update BEFORE UPDATE OF id ON skills WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'skill' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER languages_kind_insert BEFORE INSERT ON languages WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'language' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER languages_kind_update BEFORE UPDATE OF id ON languages WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'language' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER projects_kind_insert BEFORE INSERT ON projects WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'project' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE TRIGGER projects_kind_update BEFORE UPDATE OF id ON projects WHEN (SELECT kind FROM content_items WHERE id = NEW.id) IS NOT 'project' BEGIN SELECT RAISE(ABORT, 'Content kind mismatch'); END;
CREATE INDEX project_image_order ON project_images(project_id, position);
CREATE INDEX project_image_media ON project_images(media_id);
CREATE INDEX project_image_locale ON project_image_translations(locale);
CREATE INDEX project_link_order ON project_links(project_id, position);
CREATE INDEX project_link_locale ON project_link_translations(locale);
CREATE INDEX site_setting_locale ON site_setting_translations(locale);
CREATE INDEX seo_media ON seo_settings(social_media_id);
CREATE INDEX seo_locale ON seo_translations(locale);
CREATE INDEX social_visibility_order ON social_links(is_visible, display_order);
CREATE INDEX social_link_locale ON social_link_translations(locale);
