CREATE TABLE profile_contacts (id INTEGER PRIMARY KEY, profile_id INTEGER NOT NULL REFERENCES profile(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('email','phone','website')), value TEXT NOT NULL, is_public INTEGER NOT NULL DEFAULT 0 CHECK(is_public IN (0,1)), display_order INTEGER NOT NULL DEFAULT 0 CHECK(display_order >= 0));
CREATE INDEX profile_contact_order ON profile_contacts(profile_id, display_order);
ALTER TABLE experience ADD COLUMN employment_type TEXT;
CREATE TABLE experience_highlights (id INTEGER PRIMARY KEY, experience_id INTEGER NOT NULL REFERENCES experience(id) ON DELETE CASCADE, position INTEGER NOT NULL CHECK(position >= 0));
CREATE INDEX experience_highlight_order ON experience_highlights(experience_id, position);
CREATE TABLE experience_highlight_translations (highlight_id INTEGER NOT NULL REFERENCES experience_highlights(id) ON DELETE CASCADE, locale TEXT NOT NULL CHECK(locale IN ('en','fr','ar')), body TEXT NOT NULL, PRIMARY KEY(highlight_id, locale));
CREATE INDEX experience_highlight_locale ON experience_highlight_translations(locale);
CREATE TABLE experience_links (id INTEGER PRIMARY KEY, experience_id INTEGER NOT NULL REFERENCES experience(id) ON DELETE CASCADE, url TEXT NOT NULL, position INTEGER NOT NULL CHECK(position >= 0));
CREATE INDEX experience_link_order ON experience_links(experience_id, position);
ALTER TABLE certificates ADD COLUMN credential_reference TEXT;
ALTER TABLE initiative_translations ADD COLUMN purpose TEXT NOT NULL DEFAULT '';
ALTER TABLE initiative_translations ADD COLUMN outcomes TEXT NOT NULL DEFAULT '';
CREATE TABLE initiative_collaborators (id INTEGER PRIMARY KEY, initiative_id INTEGER NOT NULL REFERENCES initiatives(id) ON DELETE CASCADE, name TEXT NOT NULL, url TEXT, position INTEGER NOT NULL CHECK(position >= 0));
CREATE INDEX initiative_collaborator_order ON initiative_collaborators(initiative_id, position);
CREATE TABLE initiative_projects (initiative_id INTEGER NOT NULL REFERENCES initiatives(id) ON DELETE CASCADE, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, PRIMARY KEY(initiative_id, project_id));
CREATE INDEX initiative_project_reverse ON initiative_projects(project_id);
CREATE TABLE skill_categories (id INTEGER PRIMARY KEY, slug TEXT NOT NULL UNIQUE, display_order INTEGER NOT NULL DEFAULT 0 CHECK(display_order >= 0));
CREATE TABLE skill_category_translations (category_id INTEGER NOT NULL REFERENCES skill_categories(id) ON DELETE CASCADE, locale TEXT NOT NULL CHECK(locale IN ('en','fr','ar')), name TEXT NOT NULL, PRIMARY KEY(category_id, locale));
CREATE INDEX skill_category_locale ON skill_category_translations(locale);
ALTER TABLE skills ADD COLUMN category_id INTEGER REFERENCES skill_categories(id) ON DELETE SET NULL;
CREATE INDEX skill_category ON skills(category_id);
CREATE TABLE skill_evidence (id INTEGER PRIMARY KEY, skill_id INTEGER NOT NULL REFERENCES skills(id) ON DELETE CASCADE, content_item_id INTEGER REFERENCES content_items(id) ON DELETE CASCADE, url TEXT, CHECK((content_item_id IS NOT NULL) <> (url IS NOT NULL)));
CREATE INDEX skill_evidence_skill ON skill_evidence(skill_id);
CREATE INDEX skill_evidence_content ON skill_evidence(content_item_id);
ALTER TABLE languages ADD COLUMN certificate_id INTEGER REFERENCES certificates(id) ON DELETE SET NULL;
CREATE INDEX language_certificate ON languages(certificate_id);
ALTER TABLE project_categories ADD COLUMN cover_media_id INTEGER REFERENCES media(id) ON DELETE SET NULL;
CREATE INDEX category_cover ON project_categories(cover_media_id);
ALTER TABLE project_translations ADD COLUMN role TEXT NOT NULL DEFAULT '';
ALTER TABLE project_translations ADD COLUMN outcomes TEXT NOT NULL DEFAULT '';
ALTER TABLE site_settings ADD COLUMN theme TEXT NOT NULL DEFAULT 'light' CHECK(theme IN ('light','dark'));
CREATE TABLE navigation_items (id INTEGER PRIMARY KEY, path TEXT NOT NULL, display_order INTEGER NOT NULL DEFAULT 0 CHECK(display_order >= 0), is_visible INTEGER NOT NULL DEFAULT 0 CHECK(is_visible IN (0,1)));
CREATE INDEX navigation_order ON navigation_items(is_visible, display_order);
CREATE TABLE navigation_translations (item_id INTEGER NOT NULL REFERENCES navigation_items(id) ON DELETE CASCADE, locale TEXT NOT NULL CHECK(locale IN ('en','fr','ar')), label TEXT NOT NULL, PRIMARY KEY(item_id, locale));
CREATE INDEX navigation_locale ON navigation_translations(locale);
-- Redirect sources are paths, destinations use current category IDs, so a second
-- slug change does not create redirect chains. Resolve per locale at publish time.
CREATE TABLE category_redirects (old_slug TEXT PRIMARY KEY, category_id INTEGER NOT NULL REFERENCES project_categories(id) ON DELETE CASCADE);
CREATE INDEX category_redirect_target ON category_redirects(category_id);
