// Stable presentation roles; the text for every role lives in D1.
export const siteCopyKeys = [
  'skipLink',
  'mainNavigation',
  'languageNavigation',
  'home',
  'about',
  'projects',
  'contact',
  'downloadCv',
  'viewProjects',
  'selectedWork',
  'allProjects',
  'viewProject',
  'backToProjects',
  'education',
  'experience',
  'achievements',
  'certificates',
  'initiatives',
  'skills',
  'languages',
  'present',
  'role',
  'outcomes',
  'links',
  'technologies',
  'verify',
  'relatedProjects',
  'contactHeading',
  'emptyProjects',
  'notFoundHeading',
  'notFoundBody',
  'returnHome',
] as const;
export type SiteCopyKey = (typeof siteCopyKeys)[number];
